#
#
#       _/_/    _/                                _/    _/      _/
#    _/    _/  _/    _/_/_/    _/_/_/  _/  _/_/      _/_/_/_/_/_/_/_/  _/    _/
#   _/_/_/_/  _/  _/    _/  _/        _/_/      _/    _/      _/      _/    _/
#  _/    _/  _/  _/    _/  _/        _/        _/    _/      _/      _/    _/
# _/    _/  _/    _/_/_/    _/_/_/  _/        _/      _/_/    _/_/    _/_/_/
#                                                                        _/
#                                                                   _/_/
[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/enfocado_light.toml"
]

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "OnlyLeft"

[font]
size = 14

[font.normal]
family = "VictorMono Nerd Font"

