- name: Set up dotfiles on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure essential packages are installed
      apt:
        name:
          - git
          - stow
        state: present
        update_cache: yes
    - name: Clone the dotfiles repository
      git:
        repo: https://github.com/amir002001/dotfiles.git
        dest: /home/{{ ansible_user }}/dotfiles
        version: main
    - name: Symlink all dotfiles packages using Stow
      command: stow -t /home/{{ ansible_user }} -d /home/{{ ansible_user }}/dotfiles *
      args:
        chdir: /home/{{ ansible_user }}/dotfiles
    - name: Change ownership of dotfiles
      file:
        path: /home/{{ ansible_user }}/dotfiles
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
