- name: Set up dotfiles on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure essential packages are installed
      apt:
        name:
          - git
          - stow
        state: present
        update_cache: yes
    - name: Symlink dotfiles using GNU Stow
      command: stow -t /home/{{ ansible_user_id }} -d /home/{{ ansible_user_id }}/dotfiles .
    - name: Change ownership of dotfiles
      file:
        path: /home/{{ ansible_user_id }}/dotfiles
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
    - name: Source shell configuration (optional)
      shell: source ~/.bashrc || true
      args:
        executable: /bin/bash
